#!/bin/bash


set -e

needs_provisioning="/.provision-me"
data_dir="/data"

function setup {
  echo
  echo -e "\tCreating the superuser and database:"
  echo -e "\t  user -> \033[1m${DB_USER}\033[0m"
  echo -e "\t  pass -> \033[1m${DB_PASS}\033[0m"
  echo -e "\t  db   -> \033[1m${DB_NAME}\033[0m"
  echo

  su postgres -c "psql -q -d template1 <<-EOF
    CREATE ROLE $DB_USER WITH ENCRYPTED PASSWORD '$DB_PASS';
    ALTER ROLE $DB_USER WITH SUPERUSER;
    ALTER ROLE $DB_USER WITH LOGIN;
    CREATE EXTENSION postgis;
    CREATE EXTENSION postgis_topology;
    CREATE DATABASE $DB_NAME WITH OWNER $DB_USER TEMPLATE template1;
EOF"
}

function holdup {
  while [[ ! -e /tmp/postgresql.pid ]]; do
    sleep 1
  done

  setup && rm $needs_provisioning
}

if [[ -e $needs_provisioning ]]; then
  echo "[ Waiting for database to start... ]"

  if [[ ! "$(ls -A $data_dir)" ]]; then
    cp -R /var/lib/postgresql/9.3/main/* $data_dir
  fi

  chown -R postgres $data_dir
  chmod -R 700 $data_dir

  holdup &
fi

echo "Starting PostgreSQL..."
su postgres -c "/usr/lib/postgresql/9.3/bin/postgres -D /etc/postgresql/9.3/main"
